stages:
  data_ingestion:
    cmd: python src/ObesityRisk/pipeline/stage01_data_ingestion.py
    deps:
      - src/ObesityRisk/pipeline/stage01_data_ingestion.py
      - Config/Config.yaml
    outs:
      - artifacts/data_ingestion/data.csv

  data_transformation:
    cmd: python src/ObesityRisk/pipeline/stage02_data_transformation.py
    deps:
      - src/ObesityRisk/pipeline/stage02_data_transformation.py
      - artifacts/data_ingestion/data.csv
    outs:
      - artifacts/data_transformation/test_data.csv
      - artifacts/data_transformation/train_data.csv

  model_trainer:
    cmd: python src/ObesityRisk/pipeline/stage03_model_trainer.py
    deps: 
      - src/ObesityRisk/pipeline/stage03_model_trainer.py
      - artifacts/data_transformation/test_data.csv
      - artifacts/data_transformation/train_data.csv
    params:
      - XgbClassifier
    outs:
      - artifacts/model_trainer/scaled_train_data.csv
      - artifacts/model_trainer/scaled_test_data.csv
      - artifacts/model_trainer/model.pkl
      - artifacts/model_trainer/preprocessor.pkl
  
  model_evaluation:
    cmd: python src/ObesityRisk/pipeline/stage04_model_evaluation.py
    deps: 
      - artifacts/model_trainer/scaled_test_data.csv
      - artifacts/model_trainer/model.pkl
    outs: 
      - artifacts/model_evaluation/metrics.json

    
