artifacts_file: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/UbaleSachin/Datasets/raw/main/train.csv
  local_data_file: artifacts/data_ingestion/train_data.csv