artifacts_file: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/UbaleSachin/Datasets/raw/main/train.csv
  local_data_file: artifacts/data_ingestion/data.csv


data_transformation:
  root: artifacts/data_transformation
  data: artifacts/data_ingestion/data.csv
  train_set: artifacts/data_transformation
  test_set: artifacts/data_transformation
  #preprocessing_obj: artifacts/data_transformation


model_trainer:
  root: artifacts/model_trainer
  train_set: artifacts/data_transformation/train_data.csv
  test_set: artifacts/data_transformation/test_data.csv
  preprocessing_obj: artifacts/model_trainer    #/preprocessor.pkl
  model: artifacts/model_trainer
  scaled_train_set: artifacts/model_trainer
  scaled_test_set: artifacts/model_trainer
  data: artifacts/data_ingestion/data.csv


model_evaluation:
  root: artifacts/model_evaluation
  scaled_test_set: artifacts/model_trainer/scaled_test_data.csv
  model: artifacts/model_trainer/model.pkl
  preprocessing_obj: artifacts/model_trainer/preprocessor.pkl
  metrics: artifacts/model_evaluation/metrics.json

